language: java
jdk:
- oraclejdk9
script: mvn test -B
before_deploy:
- mvn -DskipTests package
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: w0sn5SJVAV0T4lyQSJpJ9486D+GyILvsSBCukPAgaKKPpPNVFuqouUAnrqvs1whLUnxWIs8gB7rwwwGoPV9NbBCjKTLc2BS88W5v57az4vtdOGnEI3aUAAAB0Wrfa6gg1EFyf9zlsl8y8IkTRTc9D6HB7arwKS9AsTY0dLT+LeE4PtnvlepcVoA9X7zmD6GHTIoGCqsbxFGK26GC5YRgMH1jafbxOD9lODT3s78C+92ttlFah3Wy1J6hLwimZmb6bBQ4fYE31aIgJF2jz3gWIG/6jNEjENYN9u+FoBLygFP1bqq2NoQM4ySug0sJFmAoVKZTHiDgde7NQKpO4n3jU8j0rb47E0MSE9vbfulnRE3O0hKSH7r9oIQ/aQ7MAKCICn7nfb9Q2btXYsdskx4NWj38w3Cz9yonfDNbZ760cN4ZgftWu/ghI2ESVyOUxPSKpgF4csGD4e37w+pXxh40XTytDvuukPMXNAjrZyUniE/JgrPL0/NPmgMrOtiKFl+7i4yEfJ7InSIG3Q/9V2aNRykTqVET4KfmJ2JSoq6Wfv81EdUik4uYURCVLluHVqwNV0sqSi6lpcyb+EOoxxudFrwsiRIoPQqkrgIRUnioakZFMsbsTrLk3IS4gmxxMqlWWBRRhMLzjbDJNT+uILFj/nQlYDUifyMncF06n+78T8A=
  file: target/refactor-jar-with-dependencies.jar
  on:
    tags: true
