language: java
jdk:
- oraclejdk9
script: mvn test -B
before_deploy:
- mvn -DskipTests package
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_RELEASE_API_KEY
  file: target/refactor-jar-with-dependencies.jar
  on:
    repo: TQRG/leafactor-ci
